# Generated by Django 2.1.4 on 2018-12-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portaluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portaluser',
            options={'ordering': ['firstName']},
        ),
    ]
